# Generated by Django 5.0.3 on 2024-03-17 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('more', '0007_remove_product_updated_at_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/'),
        ),
    ]
