# Generated by Django 5.0.3 on 2024-03-18 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('more', '0009_remove_product_created_at_remove_product_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
