# Generated by Django 5.0.3 on 2024-03-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('more', '0011_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
