# Generated by Django 5.0.3 on 2024-03-19 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('more', '0013_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
