# Generated by Django 5.0.3 on 2024-03-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('more', '0015_review_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, default="{static 'images/cel.png'}", upload_to='media/'),
        ),
    ]
