# Generated by Django 5.0.3 on 2024-03-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('more', '0016_alter_review_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, default='cel.png', upload_to='media/'),
        ),
    ]
