# Generated by Django 5.0.3 on 2024-03-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('more', '0025_alter_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='user',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
