# Generated by Django 5.0.3 on 2024-04-05 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('more', '0032_alter_review_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='image',
        ),
    ]
