# Generated by Django 5.0.4 on 2024-04-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("more", "0033_remove_review_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="DinoSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("color", models.CharField(default="#FF5733", max_length=7)),
            ],
        ),
    ]
